name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        create_credentials_file: true
        export_environment_variables: true
        cleanup_credentials: true
        access_token_lifetime: 3600s
        access_token_scopes: https://www.googleapis.com/auth/cloud-platform
        retries: 3
        backoff: 250
        id_token_include_email: false
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      env:
        WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

    - name: Run tests
      run: |
        pytest
